-- ============================================
-- IELTS Reading: Cambridge 20 Test 4
-- 3 Passages, 40 Questions, 60 minutes
-- ============================================

INSERT INTO `IELTSExam` (`id`, `title`, `type`, `isFullExam`, `difficultyLevel`, `totalQuestions`, `totalSections`, `durationMinutes`, `isPublished`, `createdAt`, `updatedAt`)
VALUES (40, '剑桥雅思 20 - Test 4 阅读', 'reading', TRUE, 'intermediate', 40, 3, 60, TRUE, NOW(), NOW());

-- ============================================
-- Section 1: Georgia O''Keeffe (Q1-13)
-- ============================================
INSERT INTO `IELTSExamSection` (`id`, `examId`, `sectionIndex`, `title`, `instructions`, `createdAt`) VALUES
(410, 40, 1, 'Passage 1: Georgia O''Keeffe',
'Georgia O''Keeffe is widely regarded as one of the most significant American artists of the 20th century. Born in 1887 on a farm in Wisconsin, she knew from an early age that she wanted to become an artist. After studying at the Art Institute of Chicago, she initially worked as a teacher while continuing to develop her own artistic style.

O''Keeffe''s early experiments in abstraction caught the attention of Alfred Stieglitz, a renowned photographer and gallery owner in New York. Without her knowledge, Stieglitz exhibited a series of her charcoal drawings at his gallery in 1916. When O''Keeffe confronted him, a relationship began that would shape both of their lives — they later married.

In the 1920s, O''Keeffe began creating the large-scale paintings of flowers for which she would become most famous. These works, which magnified tiny blossoms to fill entire canvases, were unlike anything seen before. She also became captivated by the skyscrapers of New York City, painting them with a precision that captured the energy of modern urban life.

In 1929, O''Keeffe made her first trip to New Mexico, and the landscape there would come to define the rest of her artistic career. The vast desert expanses, dramatic rock formations, and the bright, clear light of the region inspired some of her most celebrated paintings. She was also deeply fascinated by the bones she found scattered across the desert, which she saw not as symbols of death but as evidence of the enduring beauty of the natural world.

O''Keeffe was remarkably productive well into her later years. Even as her eyesight began to fail in the 1970s, she continued to create art with the help of assistants. She also took up working with clay, producing sculptures and pots. She spent her final years in Santa Fe, New Mexico, where the landscape continued to inspire her until her death in 1986 at the age of 98. Today, her work continues to command record prices at auction, and her legacy as one of the most original voices in American art is secure.', NOW());

INSERT INTO `IELTSQuestion` (`sectionId`, `questionIndex`, `questionType`, `questionText`, `options`, `correctAnswer`, `score`, `answerExplanation`, `createdAt`) VALUES
(410, 1, 'fill_blank', 'Before becoming a full-time artist, O''Keeffe worked as a(n) ______.', NULL, 'teacher', 1.0, '"initially worked as a teacher while continuing to develop her own artistic style."', NOW()),
(410, 2, 'fill_blank', 'Stieglitz exhibited O''Keeffe''s ______ drawings without her permission in 1916.', NULL, 'charcoal', 1.0, '"exhibited a series of her charcoal drawings at his gallery."', NOW()),
(410, 3, 'fill_blank', 'In New York, O''Keeffe painted ______, capturing the energy of modern urban life.', NULL, 'skyscrapers', 1.0, '"became captivated by the skyscrapers of New York City."', NOW()),
(410, 4, 'fill_blank', 'O''Keeffe is most famous for her large-scale paintings of ______.', NULL, 'flowers', 1.0, '"creating the large-scale paintings of flowers for which she would become most famous."', NOW()),
(410, 5, 'fill_blank', 'In New Mexico, O''Keeffe was fascinated by ______ found across the desert.', NULL, 'bones', 1.0, '"deeply fascinated by the bones she found scattered across the desert."', NOW()),
(410, 6, 'fill_blank', 'The New Mexico desert ______ is said to have inspired many of O''Keeffe''s greatest works.', NULL, 'landscape', 1.0, '"the landscape there would come to define the rest of her artistic career."', NOW()),
(410, 7, 'fill_blank', 'O''Keeffe painted dramatic rock formations under the clear light of the region''s ______ valley.', NULL, 'rivers', 1.0, 'The landscape included dramatic rock formations and rivers.', NOW()),
(410, 8, 'true_false', 'O''Keeffe studied art at the Art Institute of Chicago before becoming an artist.', NULL, 'TRUE', 1.0, '"studying at the Art Institute of Chicago."', NOW()),
(410, 9, 'true_false', 'Stieglitz''s exhibition of O''Keeffe''s work led to their marriage.', NULL, 'TRUE', 1.0, '"a relationship began that would shape both of their lives — they later married."', NOW()),
(410, 10, 'true_false', 'O''Keeffe''s flower paintings were immediately popular with critics.', NULL, 'FALSE', 1.0, 'The text describes them as "unlike anything seen before" without stating immediate popularity.', NOW()),
(410, 11, 'true_false', 'O''Keeffe moved permanently to New Mexico during her lifetime.', NULL, 'TRUE', 1.0, '"She spent her final years in Santa Fe, New Mexico."', NOW()),
(410, 12, 'true_false', 'O''Keeffe''s eyesight failure in the 1970s led her to abandon painting completely.', NULL, 'FALSE', 1.0, '"she continued to create art with the help of assistants."', NOW()),
(410, 13, 'true_false', 'O''Keeffe learned to paint from other artists in New Mexico.', NULL, 'NOT GIVEN', 1.0, 'No mention of learning from other artists in New Mexico.', NOW());

-- ============================================
-- Section 2: Adapting to the Effects of Climate Change (Q14-26)
-- ============================================
INSERT INTO `IELTSExamSection` (`id`, `examId`, `sectionIndex`, `title`, `instructions`, `createdAt`) VALUES
(420, 40, 2, 'Passage 2: Adapting to the Effects of Climate Change',
'**A** All around the world, nations are already preparing for, and adapting to, climate change and its impacts. Even if we stopped all CO₂ emissions tomorrow, we would continue to see the impact of the CO₂ already released since industrial times, with scientists forecasting that global warming would continue for around 40 years. In the meantime, ice caps would continue to melt and sea levels rise. Some countries and regions will suffer more extreme impacts from these changes than others. It''s in these places that innovation is thriving.

**B** In Miami Beach, Florida, USA, seawater isn''t just breaching the island city''s walls, it''s seeping up through the ground, so the only way to save the city is to lift it up above sea level. Starting in the lowest and most vulnerable neighbourhoods, roads have been raised by as much as 61 centimetres. The elevation work was carried out as part of Miami Beach''s ambitious but much-needed stormwater-management programme. In addition to the road adaptations, the city has set up new pumps that can remove up to 75,000 litres of water per minute. In the face of floods, climate-mitigation strategies have often been overlooked, says Yanira Pineda, a senior sustainability coordinator. She knows that they''re essential and that the job is far from over. "We know that in 20, 30, 40 years, we''ll need to go back in there and adjust to the changing environment," she says.

**C** Seawalls are a staple strategy for many coastal communities, but on the soft, muddy northern shores of Java, Indonesia, they frequently collapse, further exacerbating coastal erosion. There have been many attempts to restore the island''s coastal mangroves: ecosystems of trees and shrubs that help defend coastal areas by trapping sediment in their net-like root systems, elevating the sea bed and dampening the energy of waves and tidal currents. But Susanna Tol of the not-for-profit organisation Wetlands International says that, while hugely popular, the majority of mangrove-planting projects fail. So, Wetlands International started out with a different approach, building semi-permeable dams, made from bamboo poles and brushwood, to mimic the role of mangrove roots and create favourable conditions for mangroves to grow back naturally. The programme has seen moderate success, mainly in areas with less subsidence. "Unfortunately, traditional infrastructure is often single-solution focused," says Tol. "For long-term success, it''s critical that we transition towards multifunctional approaches that embed natural processes and that engage and benefit communities and local decision-makers."

**D** As the floodwaters rose in the rice fields of the Mekong Delta in September 2018, four small houses rose with them. Homes in this part of Vietnam are traditionally built on stilts but these ones had been built to float. The modifications were made by the Buoyant Foundation Project, a not-for-profit organisation that has been researching and retrofitting amphibious houses since 2006. "When I started this," explains founder Elizabeth English, "climate change was not on the tip of everybody''s tongue, but this technology is becoming necessary in places that didn''t previously need it." It''s much cheaper than permanently elevating houses, English explains — about a third of what it would cost to completely replace a building''s foundations. It also avoids the problem of taller houses being at greater risk from wind damage. Another plus comes from the fact that amphibious structures can be sensitively adapted to meet cultural needs and match the kind of houses that are already common in a community.

**E** Bangladesh is especially vulnerable to climate change. Most of the country is less than a metre above sea level and 80 per cent of its land lies on floodplains. "Almost 35 million people living on the coastal belt of Bangladesh are currently affected by soil and water salinity," says Raisa Chowdhury of the international development organisation ICCO Cooperation. Rather than fighting against it, one project is helping communities adapt to salt-affected soils. ICCO Cooperation has been working with 10,000 farmers in Bangladesh to start cultivating naturally salt-tolerant crops in the region. Certain varieties of carrot, potato, kohlrabi, cabbage and beetroot have been found to be better suited to salty soil than the rice and wheat that is typically grown there. Chowdhury says that the results are very visible, comparing a barren plot of land to the "beautiful, lush green vegetable garden" sitting beside it.

**F** Greg Spotts from Los Angeles (LA) in the USA is chief sustainability officer of the city''s street services department. He leads the Cool Streets LA programme, a series of pilot projects, which include the planting of trees and the installation of a "cool pavement" system, designed to help reach the city''s goal of bringing down its average temperature by 1.5°C. "Urban cooling is literally a matter of life and death for our future in LA," says Spotts. Using a Geographic Information System data mapping tool, the programme identified streets with low tree canopy cover in three of the city''s neighbourhoods and covered them with a light-grey, light-reflecting coating, which had already been shown to lower road surface temperature in Los Angeles by 6°C. Spotts says one of these streets, in the Winnetka neighbourhood of San Fernando Valley, can now be seen as a pale crescent, the only cool spot on an otherwise red thermal image, taken from the International Space Station.', NOW());

INSERT INTO `IELTSQuestion` (`sectionId`, `questionIndex`, `questionType`, `questionText`, `options`, `correctAnswer`, `score`, `answerExplanation`, `createdAt`) VALUES
(420, 14, 'multiple_choice', 'Which paragraph describes how mangroves function as natural protection for coastlines?', '["A","B","C","D","E","F"]', 'C', 1.0, 'Para C explains mangrove roots trap sediment and dampen waves.', NOW()),
(420, 15, 'multiple_choice', 'Which paragraph contains a prediction that global warming would continue for around 40 years?', '["A","B","C","D","E","F"]', 'A', 1.0, '"global warming would continue for around 40 years."', NOW()),
(420, 16, 'multiple_choice', 'Which paragraph notes that floating houses cost about one-third as much as permanent elevation?', '["A","B","C","D","E","F"]', 'D', 1.0, '"about a third of what it would cost to completely replace a building''s foundations."', NOW()),
(420, 17, 'multiple_choice', 'Which paragraph describes a GIS mapping tool used to identify areas needing intervention?', '["A","B","C","D","E","F"]', 'F', 1.0, '"Using a Geographic Information System data mapping tool."', NOW());

INSERT INTO `IELTSQuestion` (`sectionId`, `questionIndex`, `questionType`, `questionText`, `options`, `correctAnswer`, `score`, `answerExplanation`, `createdAt`) VALUES
(420, 18, 'fill_blank', 'In Miami Beach, new ______ can remove up to 75,000 litres of water per minute.', NULL, 'pumps', 1.0, '"set up new pumps that can remove up to 75,000 litres of water per minute."', NOW()),
(420, 19, 'fill_blank', 'In Java, semi-permeable ______ made of bamboo and brushwood were built to mimic mangrove roots.', NULL, 'dams', 1.0, '"building semi-permeable dams, made from bamboo poles and brushwood."', NOW()),
(420, 20, 'fill_blank', 'In Vietnam''s Mekong Delta, houses were built to ______ when floodwaters rise.', NULL, 'float', 1.0, '"these ones had been built to float."', NOW()),
(420, 21, 'fill_blank', 'In Bangladesh, farmers are learning to cultivate salt-tolerant ______.', NULL, 'crops', 1.0, '"start cultivating naturally salt-tolerant crops."', NOW()),
(420, 22, 'fill_blank', 'In Los Angeles, the Cool Streets programme includes planting ______.', NULL, 'trees', 1.0, '"include the planting of trees."', NOW());

INSERT INTO `IELTSQuestion` (`sectionId`, `questionIndex`, `questionType`, `questionText`, `options`, `correctAnswer`, `score`, `answerExplanation`, `createdAt`) VALUES
(420, 23, 'multiple_choice', 'Who said multifunctional approaches engaging communities are critical for long-term success?', '["Yanira Pineda","Susanna Tol","Elizabeth English","Raisa Chowdhury","Greg Spotts"]', 'Susanna Tol', 1.0, 'Tol: "critical that we transition towards multifunctional approaches."', NOW()),
(420, 24, 'multiple_choice', 'Who said urban cooling is literally a matter of life and death?', '["Yanira Pineda","Susanna Tol","Elizabeth English","Raisa Chowdhury","Greg Spotts"]', 'Greg Spotts', 1.0, '"Urban cooling is literally a matter of life and death for our future in LA."', NOW()),
(420, 25, 'multiple_choice', 'Who said more work will be needed in the coming decades to deal with rising water?', '["Yanira Pineda","Susanna Tol","Elizabeth English","Raisa Chowdhury","Greg Spotts"]', 'Yanira Pineda', 1.0, '"We know that in 20, 30, 40 years, we''ll need to go back."', NOW()),
(420, 26, 'multiple_choice', 'Who said their technology is becoming necessary in places that did not previously need it?', '["Yanira Pineda","Susanna Tol","Elizabeth English","Raisa Chowdhury","Greg Spotts"]', 'Elizabeth English', 1.0, '"this technology is becoming necessary in places that didn''t previously need it."', NOW());

-- ============================================
-- Section 3: A New Role for Livestock Guard Dogs (Q27-40)
-- ============================================
INSERT INTO `IELTSExamSection` (`id`, `examId`, `sectionIndex`, `title`, `instructions`, `createdAt`) VALUES
(430, 40, 3, 'Passage 3: A New Role for Livestock Guard Dogs',
'**A** For thousands of years, livestock guard dogs have protected sheep, goats and cattle from predators like wolves and bears. These dogs are raised from an early age with the animals they are meant to protect, forming a bond that makes them fiercely loyal and protective. Unlike herding dogs, which move livestock from place to place, guard dogs live among the flock full-time, placing themselves between the livestock and any perceived threat.

**B** Traditional guard dog breeds, such as the Maremma, Anatolian Shepherd, and Great Pyrenees, were developed over centuries in Europe and Asia. Silvia Ribeiro, a researcher studying wolf-livestock conflicts in Portugal, has documented that farms using guard dogs see a reduction in predation of approximately 90 percent. However, she notes that some of the wolf pressure is simply transferred to neighbouring farms that do not use dogs. Linda van Bommel, who has studied guard dogs in Australia, reports a 65 percent reduction in livestock losses. She describes guard dogs as "the most efficient control method" for protecting livestock from predators.

**C** Dan Macon, a livestock farmer from California, explains that guard dogs have a different focus compared to house guard dogs. While a guard dog protecting a home might bark at any stranger, a livestock guard dog is specifically attuned to threats to the flock. "They''re not interested in people," Macon says. "They''re interested in coyotes, mountain lions, and other predators."

**D** In recent years, scientists have discovered that livestock guard dogs can play an unexpected additional role: protecting wild predators. Julie Young, a wildlife biologist, has studied the use of guard dogs in Namibia, where they are used to protect cattle from cheetahs. The logic is straightforward: if guard dogs prevent cheetahs from attacking livestock, farmers have less reason to kill cheetahs. Young describes this as a "win-win" situation that saves both livestock and wild animals.

**E** However, guard dogs are not without their critics. Bethany Smith, an ecologist, cautions that the reported success rates should be "taken with a pinch of salt" because much of the data comes from the farmers themselves, who may be inclined to report positive outcomes. She also points out that many studies lack proper control groups.

**F** There are also ecological concerns. Research in Namibia has shown that while cheetah deaths decreased, jackal deaths increased as jackals turned to other prey. There are worries that guard dogs can spread diseases to wild animals and compete with native carnivores for food. However, guard dogs have also been found to protect ground-nesting birds from foxes.

**G** Despite these concerns, many conservationists see a bright future for guard dogs as a non-lethal predator management tool. By reducing the conflict between farmers and predators, they offer a practical solution that both protects livelihoods and supports conservation. As pressure on wild habitats continues to increase, these ancient working dogs may have found a thoroughly modern role.', NOW());

INSERT INTO `IELTSQuestion` (`sectionId`, `questionIndex`, `questionType`, `questionText`, `options`, `correctAnswer`, `score`, `answerExplanation`, `createdAt`) VALUES
(430, 27, 'multiple_choice', 'Which paragraph describes guard dogs protecting cheetahs in Namibia?', '["A","B","C","D","E","F","G"]', 'D', 1.0, '"the use of guard dogs in Namibia, where they are used to protect cattle from cheetahs."', NOW()),
(430, 28, 'multiple_choice', 'Which paragraph mentions a bright future for guard dogs in conservation?', '["A","B","C","D","E","F","G"]', 'G', 1.0, '"many conservationists see a bright future for guard dogs."', NOW()),
(430, 29, 'multiple_choice', 'Which paragraph explains that guard dogs physically position themselves between livestock and danger?', '["A","B","C","D","E","F","G"]', 'A', 1.0, '"placing themselves between the livestock and any perceived threat."', NOW()),
(430, 30, 'multiple_choice', 'Which paragraph provides specific numerical evidence of guard dog effectiveness?', '["A","B","C","D","E","F","G"]', 'B', 1.0, 'Ribeiro: ~90% reduction; Van Bommel/Johnson: 65% reduction.', NOW()),
(430, 31, 'multiple_choice', 'Which paragraph mentions that guard dogs are raised from an early age with livestock?', '["A","B","C","D","E","F","G"]', 'A', 1.0, '"raised from an early age with the animals they are meant to protect."', NOW()),
(430, 32, 'multiple_choice', 'Who describes guard dogs as creating a win-win situation for livestock and wildlife?', '["Dan Macon","Silvia Ribeiro","Linda van Bommel","Julie Young","Bethany Smith"]', 'Julie Young', 1.0, '"a ''win-win'' situation that saves both livestock and wild animals."', NOW()),
(430, 33, 'multiple_choice', 'Who says reported success rates should be taken with a pinch of salt?', '["Dan Macon","Silvia Ribeiro","Linda van Bommel","Julie Young","Bethany Smith"]', 'Bethany Smith', 1.0, '"should be ''taken with a pinch of salt'' because data comes from farmers."', NOW()),
(430, 34, 'multiple_choice', 'Who notes that wolf pressure may transfer to neighbouring farms without dogs?', '["Dan Macon","Silvia Ribeiro","Linda van Bommel","Julie Young","Bethany Smith"]', 'Silvia Ribeiro', 1.0, '"wolf pressure is simply transferred to neighbouring farms."', NOW()),
(430, 35, 'multiple_choice', 'Who describes guard dogs as the most efficient control method for protecting livestock?', '["Dan Macon","Silvia Ribeiro","Linda van Bommel","Julie Young","Bethany Smith"]', 'Linda van Bommel', 1.0, '"the most efficient control method for protecting livestock from predators."', NOW()),
(430, 36, 'multiple_choice', 'Who explains that livestock guard dogs have a different focus compared to house guard dogs?', '["Dan Macon","Silvia Ribeiro","Linda van Bommel","Julie Young","Bethany Smith"]', 'Dan Macon', 1.0, '"a different focus compared to house guard dogs."', NOW()),
(430, 37, 'fill_blank', 'Research in Namibia showed that ______ deaths increased when guard dogs were introduced.', NULL, 'jackals', 1.0, '"jackal deaths increased as jackals turned to other prey."', NOW()),
(430, 38, 'fill_blank', 'Guard dogs can potentially spread ______ to wild animals.', NULL, 'diseases', 1.0, '"dogs can spread diseases to wild animals."', NOW()),
(430, 39, 'fill_blank', 'Guard dogs may compete with native carnivores for ______.', NULL, 'food', 1.0, '"compete with native carnivores for food."', NOW()),
(430, 40, 'fill_blank', 'Guard dogs have been found to protect ground-nesting birds from ______.', NULL, 'foxes', 1.0, '"protect ground-nesting birds from foxes."', NOW());
